11 create project repository ah
Fr3dMer/softeng_module pull request #23
Opened 2023-11-30 11:27 UTC by AbiHaddon

Amended structure 
added: requirements.txt, [installation.md](http://installation.md/), user_guide.md
moved files into the correct folder and added a note to the readme file

2023-11-30 15:12 UTC, AbiHaddon commented
@Fr3dMer Just realised this branch is to merge into main .....

2023-12-01 10:46 UTC, Fr3dMer commented
Hmm I think if you click edit you can change the target branch 
![image](https://github.com/Fr3dMer/softeng_module/assets/80460761/d2a33019-83c0-4765-8f92-55f84a8553fa)

2023-12-01 11:16 UTC, Fr3dMer requested changes

2023-12-01 11:16 UTC, Fr3dMer commented on requirments.txt
> +# The requirements.txt file has been either replaced by a pyproject.toml or integrated into a pyproject.toml
#### SUGGESTION:
- It seems that pyproject.toml replaces the need for a setup.py, but does not provide a functional way to pin dependency versions like in Requirements.txt, for deployable applications it seems that both are required. This has taken me down a rabbit hole so let me know what you think 
- https://venthur.de/2022-12-18-python-packaging.html 
- https://github.com/pypa/packaging.python.org/issues/685

2023-12-01 11:16 UTC, Fr3dMer commented on src/GenePanelRepo.db
#### SUGGESTION:
- Best to have db removed from repo and have it generated during install?

2023-12-01 11:16 UTC, Fr3dMer commented on .idea/.gitignore
> +/shelf/
#### REQUEST:
- Needs to ignore python specific files 
- e.g: 
__pycache__/
*.py[cod]
*$py.class

2023-12-01 11:16 UTC, Fr3dMer commented on .idea/inspectionProfiles/profiles_settings.xml
#### COMMENT:
- Need to come back to this as I assume this is something from Petes tutorials

2023-12-05 08:10 UTC, Fr3dMer commented on requirments.txt
> +# The requirements.txt file has been either replaced by a pyproject.toml or integrated into a pyproject.toml
Interesting point thank you 😊

2023-12-11 12:10 UTC, AmyGrimwood approved these changes
Looks really good Abi.

2023-12-18 15:19 UTC, AbiHaddon commented on README.md
> +# A fully rendered markdown file (README.md) that describes the project
to be done next stage

2023-12-18 15:19 UTC, AbiHaddon commented on docs/Installation.md
> +# An installation markdown file that tells us how to run the project
to be done next stage

2023-12-18 15:19 UTC, AbiHaddon commented on requirments.txt
> +# The requirements.txt file has been either replaced by a pyproject.toml or integrated into a pyproject.toml
to consider next stage

2023-12-18 15:20 UTC, AbiHaddon commented on src/GenePanelRepo.db
yes! will do

2023-12-18 15:20 UTC, AbiHaddon commented on .idea/.gitignore
> +/shelf/
to be done next stage

2023-12-18 15:21 UTC, Fr3dMer approved these changes
As per our conversation on teams, this was laying out the structure of repo. Further detail to be achieved in next sprint

2023-12-18 15:23 UTC, merged