35 database integration
Fr3dMer/softeng_module pull request #41
Opened 2024-01-22 12:23 UTC by AbiHaddon

Script for DB integration within software. 

NB: removed database_2.0.py file from commit - see 'database second and third draft' commit - this file was the original script before wrapping script in a class. 

Note identified a potential issue:
When checking the DB for the same version, if the unique_panel_id is the same as one in the database getting the following error. 
![image](https://github.com/Fr3dMer/softeng_module/assets/128397378/c813c46d-95c8-4b1e-bf00-7abb8573c038)
Will need to be fixed - to discuss in meeting 22/01/2024 between @AmyGrimwood @Fr3dMer @AbiHaddon

2024-01-23 09:19 UTC, Fr3dMer requested changes
Looks really good, some last finishing touches requested

2024-01-23 09:19 UTC, Fr3dMer commented on src/database_3.0.py
> +        condition = or_(self.samples.columns.patient_id == input_id, self.samples.columns.sample_id == input_id)
### REQUEST
- Nice use of _or(), but what if lab has same patient_id and sample_id for different patient. Would this return multiple results for different patients?

2024-01-23 09:19 UTC, Fr3dMer commented on src/database_3.0.py
> +            return highest_version, json_query
### QUERY
- Is there much point in returning highest_version if its in json?

2024-01-23 09:19 UTC, Fr3dMer commented on src/database_3.0.py
> +    def retrieve_highest_version_json(self, r_code):
### REQUST 
- Possible to add another function using the panel_id assigned by panelapp. Something like this:
```python
def retrieve_highest_version_json(self, panel_id ):
        list_of_versions = self.connection.execute(db.select(self.panels.columns.version)
            .where(self.panels.columns.panel_id == panel_id )).fetchall()
```

2024-01-23 09:19 UTC, Fr3dMer commented on src/database_3.0.py
> +                            Column('r_code', String(255), nullable=False),
### REQUEST
- Need to add column for panel_id, the unique identifier panelapp uses internally, as some panels dont have an associated rcode (e.g https://nhsgms-panelapp.genomicsengland.co.uk/panels/166/v1.0) so need a way to search for them

2024-01-23 09:19 UTC, Fr3dMer commented on src/database_3.0.py
> +    def __init__(self, db_url='sqlite:///panel_app_db.db'):
### QUERY
- How are we ensuring we aren't overwriting the db every time the script is run?

2024-01-23 09:43 UTC, Fr3dMer commented on src/database_3.0.py
> +        list_of_unique_id_and_version = self.connection.execute(db.select(self.panels.columns.version)
### QUERY
- Is this a list of unique_id_and_version or just versions

2024-01-23 09:46 UTC, Fr3dMer commented
> Script for DB integration within software.
> 
> NB: removed database_2.0.py file from commit - see 'database second and third draft' commit - this file was the original script before wrapping script in a class.
> 
> Note identified a potential issue: When checking the DB for the same version, if the unique_panel_id is the same as one in the database getting the following error. ![image](https://private-user-images.githubusercontent.com/128397378/298582943-c813c46d-95c8-4b1e-bf00-7abb8573c038.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMDI5NjQsIm5iZiI6MTcwNjAwMjY2NCwicGF0aCI6Ii8xMjgzOTczNzgvMjk4NTgyOTQzLWM4MTNjNDZkLTk1YzgtNGIxZS1iZjAwLTdhYmI4NTczYzAzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QwOTM3NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZTE2NjZjYzYyY2UzMjc0MWEwODUwYjE1MmQ1NjZhODhmOWIwOGQ0ODFiYjIxMjM0Yjk2ODRhYTdiZWI1NzZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-luv3gB2JeyAQcvRJy_hkz_ZCNR8bdNdSICGCB9-ehY) Will need to be fixed - to discuss in meeting 22/01/2024 between @AmyGrimwood @Fr3dMer @AbiHaddon

Forgot to discuss in chat yesterday. Is this exception not catching this? 
```python
        else:
            print("Panel with the same r_code and version already exists")
            return False
```

2024-01-23 13:18 UTC, AmyGrimwood approved these changes
Some more inline commenting would help with the documentation requirements

2024-01-24 16:17 UTC, AbiHaddon commented on src/database_3.0.py
> +        condition = or_(self.samples.columns.patient_id == input_id, self.samples.columns.sample_id == input_id)
well sample no. normally starts with a unique prefix i.e. EX.... so I would have thought this wouldn't happen... what do you think?

2024-01-24 16:18 UTC, AbiHaddon commented on src/database_3.0.py
> +        if list_of_versions:
Not sure what you mean by type here?

2024-01-24 16:22 UTC, AbiHaddon commented on src/database_3.0.py
> +        list_of_unique_id_and_version = self.connection.execute(db.select(self.panels.columns.version)
Not sure what you mean here...??

2024-01-24 17:10 UTC, AbiHaddon commented
In response to your previous comment:

> Script for DB integration within software.

>NB: removed database_2.0.py file from commit - see 'database second and third draft' commit - this file was the original script >before wrapping script in a class.

>Note identified a potential issue: When checking the DB for the same version, if the unique_panel_id is the same as one in the >database getting the following error. image Will need to be fixed - to discuss in meeting 22/01/2024 between >@AmyGrimwood @Fr3dMer @AbiHaddon

>Forgot to discuss in chat yesterday. Is this exception not catching this on line 83?

        else:
          print("Panel with the same r_code and version already exists")
          return False

    I have now fixe this so I am getting the above statement.  The code was comparing the version with an entire tuple

2024-01-24 17:12 UTC, AbiHaddon commented
> Some more inline commenting would help with the documentation requireme

2024-01-24 17:15 UTC, AbiHaddon commented
> Some more inline commenting would help with the documentation requirements

2024-01-24 19:15 UTC, Fr3dMer commented on src/database_3.0.py
> +        if list_of_versions:
Mostly asking for you to add what the if statement is checking

2024-01-24 19:24 UTC, AbiHaddon commented on src/database_3.0.py
> +        if list_of_versions:
An in a comment?

2024-01-24 19:32 UTC, Fr3dMer commented on src/database_3.0.py
> +        condition = or_(self.samples.columns.patient_id == input_id, self.samples.columns.sample_id == input_id)
In my lab patient id is an int like 123 while sample id is a float like 23.12345 (dont ask, this was decided in 2008 and we're stuck with it). Is it worth assuming the lab we are making this for does not store each id as the same types, like both as ints? This is a nit picky point so happy to ignore now and add as a future feature

2024-01-24 19:34 UTC, Fr3dMer commented on src/database_3.0.py
> +        list_of_unique_id_and_version = self.connection.execute(db.select(self.panels.columns.version)
I was just confused about variable name as its called `list_of_unique_id_and_version` but from my understanding the only data going into it is `(self.panels.columns.version)`, may be getting a little lost here so please let me know if I am

2024-01-24 19:41 UTC, Fr3dMer commented on src/database_3.0.py
> +        if list_of_versions:
more like `if (list_of_versions == xyz):`

2024-01-24 20:23 UTC, AbiHaddon commented on src/database_3.0.py
> +        condition = or_(self.samples.columns.patient_id == input_id, self.samples.columns.sample_id == input_id)
I think so and I think it is sensible to add as a future feature. 'TODO' comment added to script

2024-01-24 20:25 UTC, AbiHaddon commented on src/database_3.0.py
> +        if list_of_versions:
@AbiHaddon @Fr3dMer as discussed in slack meeting 24/01/24, the following comment to be added to script. 'The if statement is checking whether the list_of_versions is not empty. In Python, an empty list evaluates to False in a boolean context, and a non-empty list evaluates to True'

2024-01-24 20:41 UTC, AbiHaddon commented on src/database_3.0.py
> +        list_of_unique_id_and_version = self.connection.execute(db.select(self.panels.columns.version)
No you are right the variable name is confusing.

Resolved issue.

2024-01-24 20:44 UTC, AbiHaddon commented
@Fr3dMer will check pep8 compliance, add doc strings, exception handling as part of sprint 5 issue

2024-01-24 20:48 UTC, AbiHaddon commented
> Some more inline commenting would help with the documentation requirements

will add commenting as part of sprint 5

2024-01-24 20:56 UTC, Fr3dMer approved these changes

2024-01-24 21:08 UTC, merged