logging script
Fr3dMer/softeng_module pull request #52
Opened 2024-01-23 16:45 UTC by AbiHaddon

Script for logging 
meets the following requirements:
- appropriate logging levels must be used i.e. debug, info, warning, error
 - Need to log unexpected exceptions
 - Logging is directed to the stream as well as a log file
 - Log level for each is selectable
 - log file is replaced by a rotating log file to prevent the disk from filling

2024-01-23 19:38 UTC, AmyGrimwood requested changes

2024-01-23 19:38 UTC, AmyGrimwood commented on src/logging_1.0.py
> +import logging
Needs a docstring at start of script

2024-01-23 19:38 UTC, AmyGrimwood commented on src/logging_1.0.py
> +class LoggerManager:
Needs a docstring documenting function of this class

2024-01-23 20:07 UTC, Fr3dMer requested changes
Looks good, just needs unit testing now

2024-01-23 20:07 UTC, Fr3dMer commented on src/logging_1.0.py
> +        formatter = logging.Formatter('%(asctime)s - %(name)s - %(module)s - %(levelname)s - %(message)s - %(lineno)d',
Over 79 char long

2024-01-24 11:59 UTC, AbiHaddon commented on src/logging_1.0.py
> +        formatter = logging.Formatter('%(asctime)s - %(name)s - %(module)s - %(levelname)s - %(message)s - %(lineno)d',
Amended line length

2024-01-24 12:01 UTC, AbiHaddon commented
Added doc strings, checked script for pep8 compliance and added exception handling

2024-01-24 12:02 UTC, AbiHaddon commented
Updated script with change requests.
Added doc string, exception handling and checked for pep8 compliance

2024-01-24 12:15 UTC, Fr3dMer requested changes
Looks good, just a few pep-8 violations to fix

2024-01-24 12:15 UTC, Fr3dMer commented on src/logging_1.0.py
> +    def __init__(self, log_file_path='your_log_file.log'):
Make the default file something more appropriate for script?

2024-01-24 12:15 UTC, Fr3dMer commented on src/logging_1.0.py
> +            formatter = logging.Formatter('%(asctime)s - %(name)s - %(module)s - '
A few lines here are over 79 char

2024-01-24 12:15 UTC, Fr3dMer commented on src/logging_1.0.py
> +            # Create a stream handler to output log messages to the console
Comment over 72 char long

2024-01-24 12:15 UTC, Fr3dMer commented on src/logging_1.0.py
> +        Custom exception handler to log uncaught exceptions.
Should docstring be at start of func?

2024-01-24 12:26 UTC, AbiHaddon commented on src/logging_1.0.py
> +    def __init__(self, log_file_path='your_log_file.log'):
Amended to PanelAppDB_log_file.log

2024-01-24 12:32 UTC, AbiHaddon commented on src/logging_1.0.py
> +            formatter = logging.Formatter('%(asctime)s - %(name)s - %(module)s - '
formatter = logging.Formatter('%(asctime)s - %(name)s - %(module)s - ' = i'm being told this line is 70 characters. Slightly confused..

2024-01-24 12:32 UTC, AbiHaddon commented on src/logging_1.0.py
> +            # Create a stream handler to output log messages to the console
Amended to 59 characters

2024-01-24 12:38 UTC, AbiHaddon commented on src/logging_1.0.py
> +            formatter = logging.Formatter('%(asctime)s - %(name)s - %(module)s - '
The preferred way of wrapping long lines is by using Python’s implied line continuation inside parentheses, brackets and braces. Long lines can be broken over multiple lines by wrapping expressions in parentheses. These should be used in preference to using a backslash for line continuation. -https://peps.python.org/pep-0008/#maximum-line-length 

Am I not doing this?

2024-01-24 14:38 UTC, Fr3dMer approved these changes
Looks good to me :)

2024-01-24 15:26 UTC, merged