51 add docstrings
Fr3dMer/softeng_module pull request #60
Opened 2024-01-25 10:38 UTC by AmyGrimwood

Please highlight any PEP8 issues you see

2024-01-25 11:34 UTC, AbiHaddon requested changes

2024-01-25 11:34 UTC, AbiHaddon commented on src/JSON_parsing.py
>                  GRch38_coord = x.get('gene_data',{}).get('ensembl_genes',{}).get('GRch38',{}).get('90',{}).get('location',{})
![image](https://github.com/Fr3dMer/softeng_module/assets/128397378/a6de55e8-056a-42e7-9865-56d6cc76974a)

Getting the above pep8 issue at line 80.

2024-01-25 11:34 UTC, AbiHaddon commented on src/JSON_parsing.py
Really nice use of docstring :). Good clear statements!

2024-01-25 11:34 UTC, AbiHaddon commented on src/JSON_parsing.py
>                  GRch38_coord = x.get('gene_data',{}).get('ensembl_genes',{}).get('GRch38',{}).get('90',{}).get('location',{})
line 102 characters long

2024-01-25 11:34 UTC, AbiHaddon commented on src/JSON_parsing.py
> +            print('KeyError:PanelApp output JSON doesn\'t contain \'genes\' or \'location\' key')
There are a few instances within script where line length is longer than 79 characters.

2024-01-25 11:58 UTC, AbiHaddon commented
@AmyGrimwood - Message from fFreddie regarding line length  'I've interpreted it as any white space before a char is counted (like "     5" is length 5) and anything after a char is not counted (like "5    " is length 1)' - so we are all on the same page

2024-01-26 10:37 UTC, AmyGrimwood commented
> As Abi's mentioned, a few lines over 79 but docstrings look good. Need to add logging at some point as well but can leave that for another branch

Am I meant to be adding logging or does that come under Abi's logging tasks?

2024-01-26 11:06 UTC, AbiHaddon commented
> > As Abi's mentioned, a few lines over 79 but docstrings look good. Need to add logging at some point as well but can leave that for another branch
> 
> Am I meant to be adding logging or does that come under Abi's logging tasks?

I don't we ever specified whether I would add logging to the rest of the code. Freddie has added logging to his code and I added logging to the rest of mine. I currently working on #54.

2024-02-14 15:52 UTC, AbiHaddon approved these changes
looks good

2024-02-14 18:48 UTC, merged