53 final amendments to code
Fr3dMer/softeng_module pull request #62
Opened 2024-01-25 18:23 UTC by AbiHaddon

added exception handling, doc string, made sure scripts are pep8 compliant using flake8 and added header to script

2024-01-25 19:00 UTC, Fr3dMer requested changes
Looks good, a few places where logging could be put but other than that I'm happy

2024-01-25 19:00 UTC, Fr3dMer commented on src/database_3.0.py
> +            print(f"Error occurred when initialising database: {e}")
Something to log?

2024-01-25 19:00 UTC, Fr3dMer commented on src/database_3.0.py
> +from sqlalchemy import MetaData, Table, Column, String, Float, LargeBinary, \
is the slash neccesary?

2024-01-25 19:00 UTC, Fr3dMer commented on src/database_3.0.py
> +            print(f"Error occurred when inserting patient record: {e}")
this should be logged

2024-01-25 19:00 UTC, Fr3dMer commented on src/database_3.0.py
> +            print(f"Error occurred when trying to insert panel record "
this should be logged

2024-01-25 19:00 UTC, Fr3dMer commented on src/database_3.0.py
> +            print(f"Error occurred when trying to retrieve"
this should be logged

2024-01-25 19:00 UTC, Fr3dMer commented on src/database_3.0.py
> +            print(f"Error occurred when trying to "
log?

2024-01-25 19:00 UTC, Fr3dMer commented on src/database_3.0.py
> +        # Close the database connection
This is something to remind me, need to close the db in main!

2024-01-25 19:23 UTC, AmyGrimwood requested changes
Looks really good, just a few comments

2024-01-25 19:23 UTC, AmyGrimwood commented on src/database_3.0.py
needs a module docstring to comply with pep8

2024-01-25 19:23 UTC, AmyGrimwood commented on src/database_3.0.py
> +            print(f"Error occurred when initialising database: {e}")
Agree

2024-01-25 20:24 UTC, AbiHaddon commented on src/database_3.0.py
![image](https://github.com/Fr3dMer/softeng_module/assets/128397378/0f92c9f4-27e5-4ac8-ba30-edd67bd5c476)
Already present - being minimised in github for some reason

2024-01-25 20:33 UTC, AbiHaddon commented on src/database_3.0.py
> +from sqlalchemy import MetaData, Table, Column, String, Float, LargeBinary, \
changed to parentheses

2024-01-25 20:37 UTC, AbiHaddon commented on src/database_3.0.py
> +            print(f"Error occurred when initialising database: {e}")
added logging

2024-01-25 20:39 UTC, AbiHaddon commented on src/database_3.0.py
> +            print(f"Error occurred when inserting patient record: {e}")
logging added

2024-01-25 20:44 UTC, AbiHaddon commented on src/database_3.0.py
> +            print(f"Error occurred when trying to insert panel record "
added logging

2024-01-25 20:49 UTC, AbiHaddon commented on src/database_3.0.py
> +            print(f"Error occurred when trying to retrieve"
logging added

2024-01-25 20:50 UTC, AbiHaddon commented on src/database_3.0.py
> +            print(f"Error occurred when trying to "
logging added

2024-01-26 11:47 UTC, Fr3dMer approved these changes
Looks good to me :)

2024-01-26 11:49 UTC, merged